projects:
  browser-domains:
    description: Localized and customizable domain lists for auto-completion in browsers.
    path: components/browser/domains
    publish: true
  browser-engine-gecko:
    description: Engine implementation based on GeckoView.
    path: components/browser/engine-gecko
    publish: true
  browser-engine-system:
    description: Engine implementation based on the system WebView.
    path: components/browser/engine-system
    publish: true
  browser-errorpages:
    description: Responsive browser error pages for Android apps.
    path: components/browser/errorpages
    publish: true
  browser-icons:
    description: A component for loading and storing website icons.
    path: components/browser/icons
    publish: true
  browser-menu:
    description: A customizable menu for browsers.
    path: components/browser/menu
    publish: true
  browser-menu2:
    description: An immutable customizable menu for browsers.
    path: components/browser/menu2
    publish: true
  browser-session-storage:
    description: Component for saving and restoring the browser state.
    path: components/browser/session-storage
    publish: true
  browser-state:
    description: Component responsible for maintaining the centralized state of a
      browser engine.
    path: components/browser/state
    publish: true
  browser-storage-sync:
    description: A syncable, Rust Places-backed implementation of core data storage.
    path: components/browser/storage-sync
    publish: true
  browser-tabstray:
    description: A tabs tray component for browsers.
    path: components/browser/tabstray
    publish: true
  browser-thumbnails:
    description: A component for loading and storing website thumbnails.
    path: components/browser/thumbnails
    publish: true
  browser-toolbar:
    description: A customizable toolbar for browsers.
    path: components/browser/toolbar
    publish: true
  compose-awesomebar:
    description: An awesomebar component showing search results matching text entered
      into the toolbar.
    path: components/compose/awesomebar
    publish: true
  compose-browser-toolbar:
    description: A customizable toolbar for browsers using Jetpack Compose.
    path: components/compose/browser-toolbar
    publish: true
  compose-cfr:
    description: A standard Contextual Feature Recommendation popup using Jetpack
      Compose.
    path: components/compose/cfr
    publish: true
  compose-engine:
    description: A component for integrating a concept-engine implementation into
      Jetpack Compose UI.
    path: components/compose/engine
    publish: true
  compose-tabstray:
    description: A customizable tabs tray using Jetpack Compose.
    path: components/compose/tabstray
    publish: true
  concept-awesomebar:
    description: An abstract definition of an awesomebar component.
    path: components/concept/awesomebar
    publish: true
  concept-base:
    description: A component for basic interfaces needed by multiple components and
      that do not warrant a standalone component.
    path: components/concept/base
    publish: true
  concept-engine:
    description: An abstract layer hiding the actual browser engine implementation.
    path: components/concept/engine
    publish: true
  concept-fetch:
    description: An abstract definition of an HTTP client for fetching resources.
    path: components/concept/fetch
    publish: true
  concept-menu:
    description: An abstract definition of a browser menu component.
    path: components/concept/menu
    publish: true
  concept-push:
    description: An abstract definition of a push service component.
    path: components/concept/push
    publish: true
  concept-storage:
    description: An abstract definition of a browser storage layer.
    path: components/concept/storage
    publish: true
  concept-sync:
    description: An abstract definition of a browser data synchronization layer.
    path: components/concept/sync
    publish: true
  concept-tabstray:
    description: An abstract definition of a tabs tray component.
    path: components/concept/tabstray
    publish: true
  concept-toolbar:
    description: An abstract definition of a toolbar component.
    path: components/concept/toolbar
    publish: true
  feature-accounts:
    description: Component for tying an account manager with the tabs feature to facilitate
      auth flows.
    path: components/feature/accounts
    publish: true
  feature-accounts-push:
    description: Feature of use cases for FxA Account that work with push support.
    path: components/feature/accounts-push
    publish: true
  feature-addons:
    description: A feature that provides for managing add-ons.
    path: components/feature/addons
    publish: true
  feature-app-links:
    description: Component opening URLs in other non-browser apps.
    path: components/feature/app-links
    publish: true
  feature-autofill:
    description: Component adding support for Android`s Autofill framework.
    path: components/feature/autofill
    publish: true
  feature-awesomebar:
    description: Component connecting a concept-toolbar with a concept-awesomebar.
    path: components/feature/awesomebar
    publish: true
  feature-containers:
    description: Feature component for working with contextual identities also known
      as containers.
    path: components/feature/containers
    publish: true
  feature-contextmenu:
    description: Component for displaying context menus for web content.
    path: components/feature/contextmenu
    publish: true
  feature-customtabs:
    description: Component for providing custom tabs functionality.
    path: components/feature/customtabs
    publish: true
  feature-downloads:
    description: Feature implementation for apps that want to use Android downloads
      manager.
    path: components/feature/downloads
    publish: true
  feature-findinpage:
    description: Feature that will subscribe to the selected session and show an UI
      for results of find in page.
    path: components/feature/findinpage
    publish: true
  feature-intent:
    description: Combining various feature components for intent processing.
    path: components/feature/intent
    publish: true
  feature-logins:
    description: Feature component for logins related features.
    path: components/feature/logins
    publish: true
  feature-media:
    description: Feature component for website media related features.
    path: components/feature/media
    publish: true
  feature-privatemode:
    description: Features used to enhance private browsing mode.
    path: components/feature/privatemode
    publish: true
  feature-prompts:
    description: Feature that will subscribe to the selected session and will handle
      all the common prompt dialogs from web content.
    path: components/feature/prompts
    publish: true
  feature-push:
    description: Feature that implements push notifications with a supported push
      service.
    path: components/feature/push
    publish: true
  feature-pwa:
    description: Feature implementation for Progressive Web Apps (PWA).
    path: components/feature/pwa
    publish: true
  feature-qr:
    description: A feature that provides functionality for scanning QR codes.
    path: components/feature/qr
    publish: true
  feature-readerview:
    description: Feature implementation providing a Reader View WebExtension.
    path: components/feature/readerview
    publish: true
  feature-recentlyclosed:
    description: Feature implementation for saving and restoring recently closed tabs
    path: components/feature/recentlyclosed
    publish: true
  feature-search:
    description: Feature implementation connecting an engine implementation with the
      search module.
    path: components/feature/search
    publish: true
  feature-serviceworker:
    description: Feature that adds support for service workers when using GeckoEngine.
    path: components/feature/serviceworker
    publish: true
  feature-session:
    description: Feature implementation connecting an engine implementation with the
      session module.
    path: components/feature/session
    publish: true
  feature-share:
    description: Feature implementation for saving and sorting recent apps used for
      sharing.
    path: components/feature/share
    publish: true
  feature-sitepermissions:
    description: A feature for showing site permission request prompts.
    path: components/feature/sitepermissions
    publish: true
  feature-syncedtabs:
    description: Feature that provides access to other devices' tabs in the same account.
    path: components/feature/syncedtabs
    publish: true
  feature-tab-collections:
    description: Feature implementation for saving, restoring and organizing collections
      of tabs.
    path: components/feature/tab-collections
    publish: true
  feature-tabs:
    description: Feature implementation connecting a tabs tray implementation with
      the session and toolbar modules.
    path: components/feature/tabs
    publish: true
  feature-toolbar:
    description: Feature implementation connecting a toolbar implementation with the
      session module.
    path: components/feature/toolbar
    publish: true
  feature-top-sites:
    description: Feature implementation for saving and removing top sites.
    path: components/feature/top-sites
    publish: true
  feature-webauthn:
    description: A feature that provides WebAuthn functionality for supported engines.
    path: components/feature/webauthn
    publish: true
  feature-webcompat:
    description: Feature that provides hotfixes for websites from Mozilla's Web Compatibility
      team
    path: components/feature/webcompat
    publish: true
  feature-webcompat-reporter:
    description: Feature that enables users to report site issues to Mozilla's Web
      Compatibility team.
    path: components/feature/webcompat-reporter
    publish: true
  feature-webnotifications:
    description: Feature component for Web Notifications.
    path: components/feature/webnotifications
    publish: true
  lib-auth:
    description: A component for various kinds of authentication mechanisms.
    path: components/lib/auth
    publish: true
  lib-crash:
    description: A generic crash reporter library that can report crashes to multiple
      services.
    path: components/lib/crash
    publish: true
  lib-crash-sentry:
    description: A crash reporter for Sentry.io that that uses lib-crash.
    path: components/lib/crash-sentry
    publish: true
  lib-crash-sentry-legacy:
    description: A crash reporter for a hosted version of Sentry that uses lib-crash.
    path: components/lib/crash-sentry-legacy
    publish: true
  lib-dataprotect:
    description: A component using AndroidKeyStore to protect user data.
    path: components/lib/dataprotect
    publish: true
  lib-fetch-httpurlconnection:
    description: An implementation of lib-fetch based on HttpUrlConnection.
    path: components/lib/fetch-httpurlconnection
    publish: true
  lib-fetch-okhttp:
    description: An implementation of lib-fetch based on OkHttp.
    path: components/lib/fetch-okhttp
    publish: true
  lib-jexl:
    description: 'Javascript Expression Language: Powerful context-based expression
      parser and evaluator.'
    path: components/lib/jexl
    publish: true
  lib-publicsuffixlist:
    description: A library for reading and using the public suffix list.
    path: components/lib/publicsuffixlist
    publish: true
  lib-push-firebase:
    description: An implementation of concept-push for the Firebase Message Service.
    path: components/lib/push-firebase
    publish: true
  lib-state:
    description: A library for maintaining application state.
    path: components/lib/state
    publish: true
  samples-browser:
    description: A simple browser composed from browser components.
    path: samples/browser
    publish: false
  samples-compose-browser:
    description: A simple browser composed from browser components using Jetpack Compose.
    path: samples/compose-browser
    publish: false
  samples-crash:
    description: An app showing the integration of the lib-crash component.
    path: samples/crash
    publish: false
  samples-dataprotect:
    description: An app demoing how to use the Dataprotect component to load and store
      encrypted data in SharedPreferences.
    path: samples/dataprotect
    publish: false
  samples-firefox-accounts:
    description: A simple app demoing Firefox Accounts integration.
    path: samples/firefox-accounts
    publish: false
  samples-glean:
    description: An app demoing how to use the Glean library to collect and send telemetry
      data.
    path: samples/glean
    publish: false
  samples-glean-library:
    description: A third-party library used by samples-glean to demonstrate multi-library
      support for Glean.
    path: samples/glean/samples-glean-library
    publish: false
  samples-sync:
    description: A simple app demoing Firefox Sync (History, Bookmarks, etc) integration.
    path: samples/sync
    publish: false
  samples-sync-logins:
    description: A simple app demoing Firefox Sync (Logins) integration.
    path: samples/sync-logins
    publish: false
  samples-toolbar:
    description: An app demoing multiple customized toolbars using the browser-toolbar
      component.
    path: samples/toolbar
    publish: false
  service-contile:
    description: A library to communicate with the Contile services API
    path: components/service/contile
    publish: true
  service-digitalassetlinks:
    description: A library for communicating with the Digital Asset Links API.
    path: components/service/digitalassetlinks
    publish: true
  service-firefox-accounts:
    description: A library for integrating with Firefox Accounts.
    path: components/service/firefox-accounts
    publish: true
  service-glean:
    description: A client-side telemetry SDK for collecting metrics and sending them
      to the Mozilla telemetry service
    path: components/service/glean
    publish: true
  service-location:
    description: A library for providing location-based services.
    path: components/service/location
    publish: true
  service-nimbus:
    description: A client-side experiment SDK
    path: components/service/nimbus
    publish: true
  service-pocket:
    description: A library to communicate with the Pocket API
    path: components/service/pocket
    publish: true
  service-sync-autofill:
    description: A library for autofilling addresses and credit cards.
    path: components/service/sync-autofill
    publish: true
  service-sync-logins:
    description: A library for integrating with Firefox Sync - Logins.
    path: components/service/sync-logins
    publish: true
  support-android-test:
    description: A collection of helpers for testing components from instrumented
      (on device) tests.
    path: components/support/android-test
    publish: true
  support-base:
    description: Base component containing building blocks for components.
    path: components/support/base
    publish: true
  support-images:
    description: A collection of helpers for handling images such as icons and thumbnails.
    path: components/support/images
    publish: true
  support-ktx:
    description: A set of Kotlin extensions.
    path: components/support/ktx
    publish: true
  support-locale:
    description: A component to allow apps to change the system defined language by
      their custom one
    path: components/support/locale
    publish: true
  support-rusterrors:
    description: A bridge for reporting Rust errors to Sentry/Glean
    path: components/support/rusterrors
    publish: true
  support-rusthttp:
    description: A bridge allowing configuration of Rust HTTP requests without directly
      depending on the application services library
    path: components/support/rusthttp
    publish: true
  support-rustlog:
    description: A bridge allowing log messages from Rust code to be sent to the log
      system in support-base
    path: components/support/rustlog
    publish: true
  support-sync-telemetry:
    description: A collection of sync-related telemetry helper classes and ping descriptions.
    path: components/support/sync-telemetry
    publish: true
  support-test:
    description: A collection of helpers for testing components (local unit tests).
    path: components/support/test
    publish: true
  support-test-appservices:
    description: A component for synchronizing Application Services' unit testing
      dependencies used in Android Components.
    path: components/support/test-appservices
    publish: true
  support-test-fakes:
    description: A collection of fake implementations for testing purposes.
    path: components/support/test-fakes
    publish: true
  support-test-libstate:
    description: A collection of helpers for testing functionality that relies on
      the lib-state component (local unit tests).
    path: components/support/test-libstate
    publish: true
  support-utils:
    description: A collection of generic helper classes.
    path: components/support/utils
    publish: true
  support-webextensions:
    description: A component containing building blocks for features implemented as
      web extensions.
    path: components/support/webextensions
    publish: true
  tooling-detekt:
    description: Custom Detekt rules for internal use.
    path: components/tooling/detekt
    publish: false
  tooling-fetch-tests:
    description: Test cases for concept-fetch implementations.
    path: components/tooling/fetch-tests
    publish: false
  tooling-glean-gradle:
    artifact-type: jar
    description: A Gradle plugin to generate code for Glean metrics.
    path: components/tooling/glean-gradle-plugin
    publish: true
  tooling-lint:
    description: Custom Lint checks for using and writing components.
    path: components/tooling/lint
    publish: false
  tooling-nimbus-gradle:
    artifact-type: jar
    description: A Gradle plugin to generate code for the Nimbus Feature API.
    path: components/tooling/nimbus-gradle-plugin
    publish: true
  ui-autocomplete:
    description: A set of components to provide autocomplete functionality.
    path: components/ui/autocomplete
    publish: true
  ui-colors:
    description: The standard set of Photon colors.
    path: components/ui/colors
    publish: true
  ui-fonts:
    description: Convenience accessor for fonts used by Mozilla.
    path: components/ui/fonts
    publish: true
  ui-icons:
    description: A collection of often used browser icons.
    path: components/ui/icons
    publish: true
  ui-tabcounter:
    description: A tab counter for browsers.
    path: components/ui/tabcounter
    publish: true
  ui-widgets:
    description: The standard set of Mozilla widgets.
    path: components/ui/widgets
    publish: true
