pull_request_rules:
  - name: MickeyMoz - Auto Merge
    conditions:
      - author=MickeyMoz
      - status-success=pr-complete
      - files~=(Gecko.kt|publicsuffixes)
    actions:
      merge:
        method: rebase
        strict: true
  - name: L10N - Auto Merge
    conditions:
      - author=mozilla-l10n-automation-bot
      - status-success=pr-complete
      - files~=(strings.xml)
    actions:
      merge:
        method: rebase
        strict: true
  - name: Needs landing - Merge
    conditions:
      - status-success=pr-complete
      - label=🛬 needs landing
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
        strict: true
