language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

sudo: false

before_install:
  - touch local.properties
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew --no-daemon clean assemble test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
