projects:
  app:
    upstream_dependencies:
    - browser-domains
    - browser-engine-gecko
    - browser-errorpages
    - browser-icons
    - browser-menu
    - browser-state
    - browser-toolbar
    - compose-awesomebar
    - compose-cfr
    - concept-awesomebar
    - concept-engine
    - concept-fetch
    - concept-menu
    - feature-app-links
    - feature-awesomebar
    - feature-contextmenu
    - feature-customtabs
    - feature-downloads
    - feature-findinpage
    - feature-intent
    - feature-media
    - feature-prompts
    - feature-search
    - feature-session
    - feature-sitepermissions
    - feature-tabs
    - feature-toolbar
    - feature-top-sites
    - feature-webcompat
    - feature-webcompat-reporter
    - lib-auth
    - lib-crash
    - lib-crash-sentry
    - lib-fetch-okhttp
    - lib-publicsuffixlist
    - lib-state
    - service-glean
    - service-location
    - service-nimbus
    - service-telemetry
    - support-ktx
    - support-locale
    - support-rusthttp
    - support-rustlog
    - support-test
    - support-test-libstate
    - support-utils
    - support-webextensions
    - ui-autocomplete
    - ui-colors
    - ui-icons
    - ui-tabcounter
