# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: "AC - Sync Strings"

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  main:
    name: "Sync Strings"
    runs-on: ubuntu-20.04
    steps:
      - name: "Discover A-C Version"
        id: ac-version-for-fenix-beta
        uses: mozilla-mobile/ac-version-for-fenix-beta@1.3.0
      - name: "Checkout Main Branch"
        uses: actions/checkout@v2
        with:
          path: main
          ref: main
      - name: "Checkout Beta Branch"
        uses: actions/checkout@v2
        with:
          path: beta
          ref: "releases_v${{ steps.ac-version-for-fenix-beta.outputs.major-ac-version }}"
      - name: "Sync Strings"
        uses: mozilla-mobile/sync-strings-action@2.0.0
        with:
          project: android-components
          src: main
          dst: beta
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: beta
          branch: automation/sync-ac-strings-${{ steps.ac-version-for-fenix-beta.outputs.major-ac-version }}
          title: "Uplift AC Strings from main to releases_v${{steps.ac-version-for-fenix-beta.outputs.major-ac-version}}"
          body: "This (automated) PR sync strings from `main` to `releases_v${{steps.ac-version-for-fenix-beta.outputs.major-ac-version}}`"
