# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: Bugzilla Format

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches:
      - main

jobs:
  bugzilla_format:
    runs-on: ubuntu-latest
    if: github.actor != 'mozilla-l10n-automation-bot' && github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]' && github.actor != 'MickeyMoz'
    steps:
      - name: Bugzilla Format
        uses: gabrielluong/bugzilla-format@1.0.1
        if: github.repository == 'mozilla-mobile/firefox-android'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
